on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - .github/workflows/cd.yml
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    # this takes a long time due to aarch64 qemu
    timeout-minutes: 1440

    permissions:
      contents: read
      packages: write

    steps:
      - name: co infuser
        uses: actions/checkout@v3
        with:
          path: infuser

      - name: co pantry
        uses: actions/checkout@v3
        with:
          repository: teaxyz/pantry
          path: pantry
          token: ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}

      - name: co cli
        uses: actions/checkout@v3
        with:
          repository: teaxyz/cli
          path: cli
          token: ${{ secrets.TEMP_JACOBS_GITHUB_PAT }}

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=branch
            type=raw,value=latest,enable={{is_default_branch}}

      - uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: docker buildx
        # this takes a long time due to aarch64 qemu
        timeout-minutes: 1440
        run: |
          for x in $(echo ${{ steps.meta.outputs.tags}}); do tags="$tags --tag $x"; done
          docker buildx build \
            --push \
            $tags \
            --platform linux/amd64,linux/arm64 \
            --file infuser/Dockerfile \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            .
